language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "nightly"  # nightly build
os: linux
dist: bionic
before_install:
- sudo apt-get install -y latex
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest